swagger: "2.0"
info:
  description: "This is the User Service API documentation for the coding assignment of Backend Intern role at Pratilipi."
  version: "1.0.0"
  title: "User Service API"
  contact:
    email: "esd18i001@iiitdm.ac.in"
host: "127.0.0.1:3002"
basePath: "/"
tags:
- name: "User Service"
  description: "CRUD Users"
schemes:
- "https"
- "http"
paths:
  /users:
    post:
      tags:
      - "User Service"
      summary: "Create user"
      description: ""
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Create a user"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successfully created user"
        "400":
          description: "mongoose `CastError` or `ValidationError`, bad inputs"
        "500":
          description: "everything else"
  /users/{userId}:
    get:
      tags:
      - "User Service"
      summary: "Read user by userId"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "Id of user to read"
        required: true
        type: "string"
      responses:
        "200":
          description: "successfully read user"
        "400":
          description: "mongoose `CastError` or `ValidationError`, bad inputs"
        "404":
          description: "user not found"
        "500":
          description: "everything else"
    put:
      tags:
      - "User Service"
      summary: "Update user by userId"
      description: ""
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "Id of user to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "updates"
        description: "Updated user object, a sub-schema of the following schema also works"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successfully updated user"
        "400":
          description: "mongoose `CastError` or `ValidationError`, bad inputs"
        "404":
          description: "user not found"
        "500":
          description: "everything else"
    delete:
      tags:
      - "User Service"
      summary: "Delete user by userId"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The id of the user to be deleted"
        required: true
        type: "string"
      responses:
        "200":
          description: "successfully deleted user"
        "400":
          description: "mongoose `CastError` or `ValidationError`, bad inputs"
        "404":
          description: "user not found"
        "500":
          description: "everything else"
definitions:
  User:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      emailId:
        type: "string"
      phoneNumber:
        type: "string"
    xml:
      name: "User"
  API Response:
    type: "object"
    properties:
      status:
        type: "integer"
      data:
        type: "object"
      message:
        type: "string"
