version: "3.8"
services:
    web:
        image: adityads1806/pratilipi-200:initial
        build: .
        ports:
            - "3000:3000"
            - "3001:3001"
            - "3002:3002"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
